title: Лиенакс
description: Пептидный восстановительный, противовоспалительный лосьон "ЛИЕНАКС" с заживляющим и омолаживающим эффектом.
copyright: © 2025

collections:
  instructions:
    output: true

defaults:
  - scope:
      path: ""
      type: "instructions"
    values:
      layout: "instruction"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - "jekyll-seo-tag"
