title: Лиенакс
description: Пиптидный восстановительный, противовоспалительный лосьон "ЛИЕНАКС" с заживляющим и омолаживающим эффектом.
copyright: © 2025

defaults:
  - scope:
      path: ""
      type: "инструкции"
    values:
      layout: "инструкция"
      permalink: "/:categories/:title"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - "jekyll-seo-tag"
