locale: ru
timezone: Europe/Moscow
url: "https://lienax.ru"
title: Лиенакс
description: Пептидный восстановительный, противовоспалительный лосьон "ЛИЕНАКС" с заживляющим и омолаживающим эффектом.
copyright: © 2025



# Exclude these files from production site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
collections:
  pages:
    output: true
    permalink: ":name"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - "jekyll-seo-tag"
  - "jekyll-sitemap"
